name: "integration-test"

volumes:
  shared:

services:
  syncer:
    build:
      context: docker/syncer
    volumes:
      - shared:/shared
  source:
    build:
      context: docker/source
    ports:
      - "2122:22"
    volumes:
      - shared:/shared
  